curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/D3DCompiler_33.dll" --output D3DCompiler_33.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/D3DCompiler_34.dll" --output D3DCompiler_34.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/D3DCompiler_35.dll" --output D3DCompiler_35.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/D3DCompiler_36.dll" --output D3DCompiler_36.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/D3DCompiler_37.dll" --output D3DCompiler_37.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/D3DCompiler_38.dll" --output D3DCompiler_38.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/D3DCompiler_39.dll" --output D3DCompiler_39.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/D3DCompiler_40.dll" --output D3DCompiler_40.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/D3DCompiler_41.dll" --output D3DCompiler_41.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/D3DCompiler_42.dll" --output D3DCompiler_42.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/D3DCompiler_43.dll" --output D3DCompiler_43.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/D3DCompiler_44.dll" --output D3DCompiler_44.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dcompiler_47.dll" --output d3dcompiler_47.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dcsx_42.dll" --output d3dcsx_42.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dcsx_43.dll" --output d3dcsx_43.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dscache.dll" --output d3dscache.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/D3DX9_24.dll" --output D3DX9_24.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dx9_25.dll" --output d3dx9_25.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dx9_26.dll" --output d3dx9_26.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dx9_27.dll" --output d3dx9_27.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dx9_28.dll" --output d3dx9_28.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dx9_29.dll" --output d3dx9_29.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dx9_30.dll" --output d3dx9_30.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dx9_31.dll" --output d3dx9_31.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dx9_32.dll" --output d3dx9_32.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dx9_33.dll" --output d3dx9_33.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dx9_34.dll" --output d3dx9_34.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dx9_35.dll" --output d3dx9_35.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dx9_36.dll" --output d3dx9_36.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dx9_37.dll" --output d3dx9_37.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dx9_38.dll" --output d3dx9_38.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dx9_39.dll" --output d3dx9_39.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dx9_40.dll" --output d3dx9_40.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dx9_41.dll" --output d3dx9_41.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dx9_42.dll" --output d3dx9_42.dll
curl "https://zephyrgddp.github.io/DLLlib/dlls/dx9/d3dx9_43.dll" --output d3dx9_43.dll